trigger: none

stages:

- stage: DEV
  variables:
    storageAccount: angulardevstorage001

  jobs:
  - deployment: DeployDev
    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo "Deploying to DEV"
              echo "$(storageAccount)"
            displayName: 'Test DEV'

- stage: TEST
  dependsOn: DEV

  jobs:
  - deployment: DeployTest
    environment: test

    strategy:
      runOnce:
        deploy:
          steps:

          - script: echo "Deploying to TEST"

- stage: STAGE
  dependsOn: TEST

  jobs:
  - deployment: DeployStage
    environment: stage

    strategy:
      runOnce:
        deploy:
          steps:

          - script: echo "Deploying to STAGE"

- stage: PROD
  dependsOn: STAGE

  jobs:
  - deployment: DeployProd
    environment: prod

    strategy:
      runOnce:
        deploy:
          steps:

          - script: echo "Deploying to PROD"