trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1
  inputs:
    version: '24.x'
  displayName: 'Use Node.js'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: ng build --configuration production
  displayName: 'Build Angular Application'

# ADD THIS STEP HERE
- script: |
    echo "Listing dist folder"
    ls -R dist
  displayName: 'Verify Build Output'

# THEN UPLOAD
- task: AzureCLI@2
  displayName: 'Upload Files to Static Website'
  inputs:
    azureSubscription: 'Azure-StaticWebsite-SC'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch \
        --account-name 'angularwebstorage001' \
        --destination '$web' \
        --source dist/hello-world-app \
        --overwrite \
        --auth-mode login