trigger: none

resources:
  pipelines:
  - pipeline: angularBuild
    source: kalyani-git-cloud.Angular-static-website

stages:

# DEV
- stage: DEV
  jobs:
  - deployment: DeployDev
    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - download: angularBuild
            artifact: AngularBuild

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure-StaticWebsite-SC'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch \
                  --account-name angulardevstorage001 \
                  --destination '$web' \
                  --source "$(Pipeline.Workspace)/angularBuild/AngularBuild" \
                  --overwrite

# TEST
- stage: TEST
  dependsOn: DEV

  jobs:
  - deployment: DeployTest
    environment: test

    strategy:
      runOnce:
        deploy:
          steps:

          - download: angularBuild
            artifact: AngularBuild

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure-StaticWebsite-SC'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch \
                  --account-name angularteststorage001 \
                  --destination '$web' \
                  --source "$(Pipeline.Workspace)/angularBuild/AngularBuild" \
                  --overwrite

# STAGE
- stage: STAGE
  dependsOn: TEST

  jobs:
  - deployment: DeployStage
    environment: stage

    strategy:
      runOnce:
        deploy:
          steps:

          - download: angularBuild
            artifact: AngularBuild

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure-StaticWebsite-SC'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch \
                  --account-name angularstagestorage001 \
                  --destination '$web' \
                  --source "$(Pipeline.Workspace)/angularBuild/AngularBuild" \
                  --overwrite

# PROD
- stage: PROD
  dependsOn: STAGE

  jobs:
  - deployment: DeployProd
    environment: prod

    strategy:
      runOnce:
        deploy:
          steps:

          - download: angularBuild
            artifact: AngularBuild

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Azure-StaticWebsite-SC'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob upload-batch \
                  --account-name angularprodstorage001 \
                  --destination '$web' \
                  --source "$(Pipeline.Workspace)/angularBuild/AngularBuild" \
                  --overwrite